owner: buckbanzai
repo: status-gruezi-net

sites:
  - name: Mastodon
    url: https://mastodon.gruezi.net
  - name: Mastodon CDN (Media & Files)
    url: https://files.gruezi.net
    expectedStatusCodes:
      - 403 # CDN should always respond with a 403, as there isn't an index page
  - name: gruezi.net Landing Page
    url: https://gruezi.net

status-website:
  cname: status.gruezi.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: gruezi.net Status
  introTitle: "This page monitors the status of the various services that are operated by gruezi.net."
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
